project:
  type: website
  output-dir: "docs"
  render:
    - dashboard/index.qmd
    - dashboard/notebooks/index.qmd
    - dashboard/about.qmd

website:
  title: "Pumatécnicos"
  navbar:
    left:
      - href: dashboard/index.qmd
        text: Inicio
      - href: dashboard/notebooks/index.qmd
        text: Dashboards

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



