project:
  type: website
  output-dir: "docs"
  render:
    - dashboard/*.qmd
    - dashboard/notebooks/*.qmd

website:
  title: "Pobreza en México"
  navbar:
    left:
      - href: dashboard/index.qmd
        text: Inicio
      - href: dashboard/notebooks/enfoque_monetario.qmd
        text: Enfoque Monetario
      - text: Enfoque de Carencias Sociales
        menu:
          - href: dashboard/notebooks/enfoque_carencias.qmd
            text: "Introducción y ODS 1"
          - text: "---"
          - href: dashboard/notebooks/ods2.qmd
            text: "ODS 2: Hambre Cero"
          - href: dashboard/notebooks/ods4.qmd
            text: "ODS 4: Educación de Calidad"
      - href: dashboard/notebooks/ods9.qmd
        text: Enfoque de Capacidades

format:
  html:
    theme:
      - cosmo
      - dashboard/custom.scss
    toc: false